name: RunOn
options:
  bundleIdPrefix: com.flexrpl
  deploymentTarget:
    iOS: 17.0

packages:
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: 8.0.0
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    from: 5.10.2

targets:
  RunOn:
    type: application
    platform: iOS
    sources:
      - RunOn
    dependencies:
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
      - package: Alamofire
    settings:
      base:
        INFOPLIST_FILE: RunOn/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.flexrpl.RunOn
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: ""
        PROVISIONING_PROFILE_SPECIFIER: ""
        RUNON_CLIENT_ID: ${RUNON_CLIENT_ID}
    info:
      path: RunOn/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLSchemes:
            - ${RUNON_CLIENT_ID}
        GIDClientID: ${RUNON_CLIENT_ID}

  RunOnTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - RunOnTests
    dependencies:
      - target: RunOn
      - package: Alamofire
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift

  RunOnUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - RunOnUITests
    dependencies:
      - target: RunOn
      - package: Alamofire
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift 