name: RunOn
options:
  bundleIdPrefix: com.flexrpl
  deploymentTarget:
    iOS: 17.0
  xcodeVersion: "15.1"

settings:
  base:
    SWIFT_INSTALL_OBJC_HEADER: YES
    SWIFT_OBJC_INTERFACE_HEADER_NAME: "$(PRODUCT_MODULE_NAME)-Swift.h"
    CLANG_ENABLE_MODULES: YES
    DEFINES_MODULE: YES
    ENABLE_BITCODE: NO
    ENABLE_TESTABILITY: YES
    OTHER_LDFLAGS: ["-ObjC"]

packages:
  AppAuth:
    url: https://github.com/openid/AppAuth-iOS
    exactVersion: 1.7.3
  GTMAppAuth:
    url: https://github.com/google/GTMAppAuth
    exactVersion: 4.1.1
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    exactVersion: 8.0.0
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    exactVersion: 5.10.2

targets:
  RunOn:
    type: application
    platform: iOS
    sources:
      - RunOn
    dependencies:
      - package: AppAuth
        product: AppAuthCore
      - package: AppAuth
        product: AppAuth
      - package: GTMAppAuth
        product: GTMAppAuth
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
      - package: Alamofire
        product: Alamofire
    settings:
      base:
        INFOPLIST_FILE: RunOn/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.flexrpl.RunOn
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: ""
        PROVISIONING_PROFILE_SPECIFIER: ""
        RUNON_CLIENT_ID: ${RUNON_CLIENT_ID}
        OTHER_LDFLAGS: [
          "-ObjC",
          "-framework", "SafariServices",
          "-framework", "LocalAuthentication",
          "-framework", "AuthenticationServices",
          "-framework", "Security",
          "-framework", "SystemConfiguration"
        ]
        ENABLE_BITCODE: NO
        ENABLE_TESTABILITY: YES
        SWIFT_INSTALL_OBJC_HEADER: YES
        DEFINES_MODULE: YES
        SWIFT_OBJC_INTERFACE_HEADER_NAME: "$(PRODUCT_MODULE_NAME)-Swift.h"
        CLANG_ENABLE_MODULES: YES
        FRAMEWORK_SEARCH_PATHS: ["$(inherited)", "$(SRCROOT)/DerivedData/SourcePackages/checkouts/**"]
    info:
      path: RunOn/Info.plist
      properties:
        CFBundleURLTypes:
          - CFBundleURLSchemes:
            - ${RUNON_CLIENT_ID}
        GIDClientID: ${RUNON_CLIENT_ID}

  RunOnTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - RunOnTests
    dependencies:
      - target: RunOn
      - package: AppAuth
        product: AppAuthCore
      - package: AppAuth
        product: AppAuth
      - package: GTMAppAuth
        product: GTMAppAuth
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
      - package: Alamofire
        product: Alamofire
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.flexrpl.RunOnTests
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: ""
        OTHER_LDFLAGS: [
          "-ObjC",
          "-framework", "SafariServices",
          "-framework", "LocalAuthentication",
          "-framework", "AuthenticationServices",
          "-framework", "Security",
          "-framework", "SystemConfiguration"
        ]
        SWIFT_INSTALL_OBJC_HEADER: YES
        DEFINES_MODULE: YES
        CLANG_ENABLE_MODULES: YES
        FRAMEWORK_SEARCH_PATHS: ["$(inherited)", "$(SRCROOT)/DerivedData/SourcePackages/checkouts/**"]

  RunOnUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - RunOnUITests
    dependencies:
      - target: RunOn
      - package: AppAuth
        product: AppAuthCore
      - package: AppAuth
        product: AppAuth
      - package: GTMAppAuth
        product: GTMAppAuth
      - package: GoogleSignIn
        product: GoogleSignIn
      - package: GoogleSignIn
        product: GoogleSignInSwift
      - package: Alamofire
        product: Alamofire
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: com.flexrpl.RunOnUITests
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_IDENTITY: ""
        OTHER_LDFLAGS: [
          "-ObjC",
          "-framework", "SafariServices",
          "-framework", "LocalAuthentication",
          "-framework", "AuthenticationServices",
          "-framework", "Security",
          "-framework", "SystemConfiguration"
        ]
        SWIFT_INSTALL_OBJC_HEADER: YES
        DEFINES_MODULE: YES
        CLANG_ENABLE_MODULES: YES
        FRAMEWORK_SEARCH_PATHS: ["$(inherited)", "$(SRCROOT)/DerivedData/SourcePackages/checkouts/**"] 