name: Build and Test

on:
  push:
    branches: [ main, mvp ]
  pull_request:
    branches: [ main, mvp ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Run tests and linting
      run: |
        cd backend
        bash scripts/format_and_lint.sh
        
    - name: Store coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: backend/coverage.xml

  sonarcloud:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Download coverage report
      uses: actions/download-artifact@v3
      with:
        name: coverage-report
        path: backend
    
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}