name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Shallow clones disabled for better SonarCloud reporting

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run formatters and linters
      run: |
        cd backend
        bash scripts/format_and_lint.sh

    - name: Run security checks
      run: |
        cd backend
        pip install bandit safety
        bandit -r . -c pyproject.toml
        safety check

    - name: Run tests with coverage
      run: |
        cd backend
        pytest --cov=. --cov-report=xml --cov-report=term-missing

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-scan-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=flexrpl
          -Dsonar.projectKey=fleXRPL_RunOn
          -Dsonar.python.coverage.reportPaths=backend/coverage.xml
          -Dsonar.sources=backend
          -Dsonar.tests=backend/tests