name: iOS CI

on:
  push:
    branches: [ main, iOS-frontend ]
    paths:
      - 'ios/**'
      - '.github/workflows/ios.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ios/**'
      - '.github/workflows/ios.yml'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14

    env:
      DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      RUNON_CLIENT_ID: ${{ secrets.RUNON_CLIENT_ID }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Show Build Environment
      run: |
        xcodebuild -version
        swift --version
        xcrun simctl list devices
        pwd
        ls -R ios/
    
    - name: Install Dependencies
      run: |
        cd ios/scripts
        chmod +x setup.sh
        ./setup.sh
    
    - name: Build
      working-directory: ios/RunOn
      run: |
        echo "📍 Working directory: $(pwd)"
        ls -la
        xcodebuild -list -project RunOn.xcodeproj || (echo "⚠️ Project file issue detected" && exit 1)
        xcodebuild clean build \
          -project RunOn.xcodeproj \
          -scheme RunOn \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=YES
    
    - name: Run Tests
      working-directory: ios/RunOn
      run: |
        xcodebuild test \
          -project RunOn.xcodeproj \
          -scheme RunOn \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2" \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          -resultBundlePath TestResults.xcresult
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: test-results
        path: ios/RunOn/TestResults.xcresult 