name: iOS CI

on:
  push:
    branches: [ main, iOS-frontend ]
    paths:
      - 'ios/**'
      - '.github/workflows/ios.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ios/**'
      - '.github/workflows/ios.yml'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Install Dependencies
      run: |
        cd ios/RunOn
        chmod +x ../scripts/setup.sh
        ../scripts/setup.sh
    
    - name: Build
      run: |
        cd ios/RunOn
        xcodebuild clean build -scheme RunOn -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2"
    
    - name: Run Tests
      run: |
        cd ios/RunOn
        xcodebuild test -scheme RunOn -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2" -resultBundlePath TestResults.xcresult
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: test-results
        path: ios/RunOn/TestResults.xcresult 