name: iOS CI

on:
  push:
    branches: [ main, iOS-frontend ]
    paths:
      - 'ios/**'
      - '.github/workflows/ios.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ios/**'
      - '.github/workflows/ios.yml'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Validate Xcode Project
      run: |
        cd ios/RunOn
        plutil -lint RunOn.xcodeproj/project.pbxproj
    
    - name: Install Dependencies
      run: |
        cd ios/RunOn
        chmod +x ../scripts/setup.sh
        ../scripts/setup.sh
    
    - name: Build
      run: |
        cd ios/RunOn
        xcodebuild -list
        xcodebuild clean build -project RunOn.xcodeproj -scheme RunOn -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    
    - name: Run Tests
      run: |
        cd ios/RunOn
        xcodebuild test -project RunOn.xcodeproj -scheme RunOn -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO -resultBundlePath TestResults.xcresult
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: test-results
        path: ios/RunOn/TestResults.xcresult 