name: iOS CI

on:
  push:
    branches: [ main, iOS-frontend ]
    paths:
      - 'ios/**'
      - '.github/workflows/ios.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'ios/**'
      - '.github/workflows/ios.yml'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-14

    env:
      DEVELOPER_DIR: /Applications/Xcode_15.2.app/Contents/Developer
      RUNON_CLIENT_ID: ${{ secrets.RUNON_CLIENT_ID }}
      DERIVED_DATA_PATH: "DerivedData"

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'
    
    - name: Install xcodegen
      run: |
        brew install xcodegen
    
    - name: Show Build Environment
      run: |
        xcodebuild -version
        swift --version
        xcrun simctl list devices
        pwd
        ls -R ios/
    
    - name: Regenerate Project
      run: |
        cd ios/scripts
        chmod +x regenerate_project.sh
        ./regenerate_project.sh
    
    - name: Clean Build Folder
      working-directory: ios/RunOn
      run: |
        rm -rf $DERIVED_DATA_PATH
        mkdir -p $DERIVED_DATA_PATH
    
    - name: Resolve Package Dependencies
      working-directory: ios/RunOn
      run: |
        xcodebuild -resolvePackageDependencies \
          -scheme RunOn \
          -clonedSourcePackagesDirPath $DERIVED_DATA_PATH/SourcePackages
    
    - name: Build and Test
      working-directory: ios/RunOn
      run: |
        xcodebuild clean test \
          -scheme RunOn \
          -destination "platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2" \
          -derivedDataPath $DERIVED_DATA_PATH \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          ONLY_ACTIVE_ARCH=YES \
          | xcpretty && exit ${PIPESTATUS[0]}
    
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: test-results
        path: ios/RunOn/DerivedData/Logs/Test/*.xcresult 